### ISSUE TITLE
Unmarshalling from JSON fails

### ISSUE THREAD

**Issue by stguitar** [springload/ssm-parent#4]
This is a great utility which will solve a critical issue for me.  However, when i try any of the functions provided I am getting the following error:

`* Can't unmarshal json from '/ecs/app/service/env/s3Bucket': invalid character 'a' looking for beginning of value`

It does not seem that the type matters... I just cannot get any properties to parse properly. 

any Idea what I am doing wrong?

I am calling the command with:

`AWS_REGION=us-east-X ssm-parent print -p /ecs/app/service -r`

**Comment by ekini** [comment]
Hi @stguitar 
Can you show me what you have in the parameters? They have to be a valid json, such as:
```json
{
  "PARAMETER1": "value1",
  "PARAMETER2": "value2"
}
```

**Comment by stguitar** [comment]
@ekini Interesting, so you are saying that in the SSM Parameter store the value field has to be JSON?  I was hoping to just store a literal string for a given path...

So for example, this is what one of mine looks like in AWS Systems Manager > Parameter Store

![paramstoreexample](https://user-images.githubusercontent.com/607525/49607954-6d908100-f965-11e8-9329-b3629494687f.png)

**Comment by ekini** [comment]
That's correct. This approach allows to store multiple environmental variables in one SSM Parameter, while allowing them to be overridden.

Just wondering, if you store a literal value in the field, what would be the environmental variable name? The `basename /long/path/here`?

**Comment by stguitar** [comment]
@ekini :D  that is the next challenge i was going to have, but essentially my assumption would be that if it were named as `/path/to/varName` that your utility would basically slap the string literal into an environment variable called literrally `varName`.  I basically named all my paths to match with my previously used environment vars.

**Comment by ekini** [comment]
If you are not in rush, I might try to implement it in the next couple of days.

**Comment by stguitar** [comment]
that would be cool - I also just loaded Go on my machine (which I've never developed on) and thought id give it a whirl, but you will definitely do it more correctly/faster than me.

**Comment by stguitar** [comment]
@ekini eh, yea i ran into dev environment issues with go that i just dont understand :D  i will wait to see what you can crank out - thank you!!

**Comment by ekini** [comment]
Hi @stguitar ! Please try https://github.com/springload/ssm-parent/releases/tag/v1.0 with the following:
```
AWS_REGION=us-east-X ssm-parent print --plain-path /ecs/app/service -r
```

**Comment by stguitar** [comment]
@ekini dude, this is fantastic, thank you.  Seems to work perfectly.

**Comment by stguitar** [comment]
@ekini I dont know if this is a bug or not, but just letting you know that if you happen to have a JSON formatted value in the tree, when it gets pulled in from plain-path it will escape it.  so basically, you wouldnt probably wanna mix/match between string literals and JSON values. This wont impact me, but figured I would let you know in case you were curious.

**Comment by ekini** [comment]
Well, I think it's hard to detect it automatically, so those cases might be worked around by using `--name` and `--plain-name` instead of paths.
