### ISSUE TITLE
Sometimes this will not retrieve parameters

### ISSUE THREAD

**Issue by stguitar** [springload/ssm-parent#6]
I started actually using this in my environments and I have about 7 containers trying to usethis on ECS. 
 All run on the same type of machines, in the same ECS Cluster. 

On 2 of my containers, I am getting the following for all attempted plain paths or names:

```
Can't get parameters from path '<my path>': RequestError: send request failed
https://ssm.us-east-2.amazonaws.com/: x509: certificate signed by unknown authority
```
The tasks restart and keep try but this continues for these containers every time.
Any ideas?

**Comment by stguitar** [comment]
AH, I think i figured this one out!

Seems these particular containers are using alpine and do not have all the same certs installed.  I will report back and close this when I test it out.

**Comment by stguitar** [comment]
yup that was it!

**Comment by ekini** [comment]
Oh, this is the issue I've had a couple of times :)
For clarity, if an image is based on Alpine, make sure you install `ca-certificates`.
```
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
```
