### ISSUE TITLE
Some properties with similar names are not being returned

### ISSUE THREAD

**Issue by stguitar** [springload/ssm-parent#7]
I have a few properties like `mailHost` and `mailHostPort`, as well as `databaseUsername` and `mailUsername`.  For each of these pairs, i only get one entry returned in the result, but not both.  As a work around i have to specifically list all 4 of these out in the parameters, but I would much prefer to not have to do that.

**Comment by ekini** [comment]
If I understand the question correctly, then if you have those properties under one path, like so:
```
/myproject/myenvironment/mailHost
/myproject/myenvironment/mailHostPort
/myproject/myenvironment/databaseUsername
/myproject/myenvironment/mailUsername
```
then you can just use `ssm-parent --plain-path /myproject/myenvironment/` with optional `-r` if you have some variables even further down the path tree.

**Comment by stguitar** [comment]
Actually, as I was trying to build out an example and it seems the issue is with the AWS CLI, not ssm-parent.  maybe you have seen this though? 

It seems as though when i issue `aws ssm get-parameters-by-path` it will return 10 entries only, when i have more. this is excluding the ones I noticed being excluded and I thought it was name related in ssm-parent. 

is it possible that pagination should be handled differently?

**Comment by stguitar** [comment]
OK, yes im having a pagination issue here.  Does ssm-parent use --no-paginate or something, or use the provided tokens to paginate through the results?

**Comment by ekini** [comment]
Good point. It doesn't handle many parameters correctly at the moment. I'll fix it.

**Comment by stguitar** [comment]
thank you, if I were able to contribute in Go id chip in.

**Comment by ekini** [comment]
Should be working correctly now :)

**Comment by stguitar** [comment]
I downloaded the darwin executable and im still only getting 10 items back for something that has more than 10.

**Comment by stguitar** [comment]
@ekini if it helps, i updated my aws cli to be the following as well:

`aws-cli/1.16.80 Python/2.7.10 Darwin/17.4.0 botocore/1.12.70`

**Comment by ekini** [comment]
Ok, will investigate.

**Comment by ekini** [comment]
Huh, sorry for that. I should've checked documentation instead of relying on my memory.
Fill test params:
```
for x in `seq 1 20`; do aws ssm put-parameter --name "/testpath/parameter_${x}" --value "value_${x}" --type String; done
```
Test params:
```
ssm-parent --plain-path /testpath -r print 
2018/12/24 10:01:37  info {
  "parameter_1": "value_1",
  "parameter_10": "value_10",
  "parameter_11": "value_11",
  "parameter_12": "value_12",
  "parameter_13": "value_13",
  "parameter_14": "value_14",
  "parameter_15": "value_15",
  "parameter_16": "value_16",
  "parameter_17": "value_17",
  "parameter_18": "value_18",
  "parameter_19": "value_19",
  "parameter_2": "value_2",
  "parameter_20": "value_20",
  "parameter_3": "value_3",
  "parameter_4": "value_4",
  "parameter_5": "value_5",
  "parameter_6": "value_6",
  "parameter_7": "value_7",
  "parameter_8": "value_8",
  "parameter_9": "value_9"
}
```
It's been fixed by https://github.com/springload/ssm-parent/commit/0f5aa8a3c30decbae39514351dfc66f38afd5a36 in https://github.com/springload/ssm-parent/releases/tag/v1.1.0

**Comment by stguitar** [comment]
@ekini hot dog, you got it! looks great!

Thank you!
